apiVersion: v1
kind: Service
metadata:
  name: pluk-ui
spec:
  ports:
  - name: http
    nodePort: 30001
    port: 8900
    protocol: TCP
    targetPort: 8900
  selector:
    app.kubernetes.io/name: pluk-ui
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}